# Generated by Django 6.1 on 2026-08-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0002_alter_deposit_coin_alter_deposit_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_username',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], default='USER', max_length=10),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='coin',
            field=models.CharField(default='USDT', max_length=20),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='network',
            field=models.CharField(default='TRC20', max_length=20),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='reference',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='investor_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
